apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique-frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: boutique-frontend

  template:
    metadata:
      labels:
        app: boutique-frontend

    spec:
      containers:
      - name: frontend

        image: us-central1-docker.pkg.dev/playground-s-11-f6bb753e/online-boutique/online-boutique:v2

        ports:
        - containerPort: 8080